package:
  name: dlib
  version: "19.2"

source:
  fn: dlib-19.2.tar.gz
  url: http://sourceforge.net/projects/dclib/files/dlib/v19.2/dlib-19.2.tar.bz2/download
  sha1: c7c21545176124cc4fe7485dd9872b2b26ea941c

  patches:
    - cmake_static_boost.patch  # [win]

build:
  number: 2

requirements:
  build:
   - python
   - cmake
   - numpy >=1.10
   - boost-gcc5 1.59.0
   # On OSX Davis has forced building the static version
   # On Windows there is a conflict between this jpeg and windows.h
   - jpeg            # [linux]
   - libpng 1.6.*
   - sqlite 3.*      # [unix]

  run:
   - python
   - numpy >=1.10
   - boost-gcc5 1.59.0
   - jpeg            # [linux]
   - libpng 1.6.*
   - sqlite 3.*      # [unix]

test:
  requires:
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost Software License
